/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface GetAccountsInterface extends utils.Interface {
  functions: {
    "accounts(uint256)": FunctionFragment;
    "update(string[])": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "accounts" | "update"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "accounts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "update", values: [string[]]): string;

  decodeFunctionResult(functionFragment: "accounts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "update", data: BytesLike): Result;

  events: {
    "UpdatedMessages(string[],string[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "UpdatedMessages"): EventFragment;
}

export interface UpdatedMessagesEventObject {
  staleAccounts: string[];
  refreshedAccounts: string[];
}
export type UpdatedMessagesEvent = TypedEvent<
  [string[], string[]],
  UpdatedMessagesEventObject
>;

export type UpdatedMessagesEventFilter = TypedEventFilter<UpdatedMessagesEvent>;

export interface GetAccounts extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GetAccountsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    accounts(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    update(
      refreshedAccounts: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  accounts(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  update(
    refreshedAccounts: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    accounts(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    update(
      refreshedAccounts: string[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "UpdatedMessages(string[],string[])"(
      staleAccounts?: null,
      refreshedAccounts?: null
    ): UpdatedMessagesEventFilter;
    UpdatedMessages(
      staleAccounts?: null,
      refreshedAccounts?: null
    ): UpdatedMessagesEventFilter;
  };

  estimateGas: {
    accounts(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    update(
      refreshedAccounts: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    accounts(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    update(
      refreshedAccounts: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
